device: cpu
tag: dev

net:
  num_layers: 4
  dim: 128

train:
  gradient_epochs: 1
  lr: 0.0001
  batch_size: 4
  show_every: 1

self_play:
  num_games: 4
  max_len: 15

pit:
  num_games: 4
  max_len: 15
  every: 1
