[project]
name = "century-rl"
version = "0.1.0"
description = "Reinforcement learning framework for board games"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "tqdm",
    "cython",
    "fastapi[standard]",
    "natsort",
    "crayons",
    "psutil",
    "pytest",
    "pytest-timeout",
    "matplotlib",
]

[dependency-groups]
dev = ["mypy"]

[project.optional-dependencies]
trackio = ["trackio>=0.38.1"]

[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["boardrl*"]
