device: cuda
tag: century

net:
  num_layers: 8
  dim: 512

train:
  gradient_epochs: 1
  lr: 0.00001
  batch_size: 32
  show_every: 1

self_play:
  num_games: 64
  max_len: 200

pit:
  num_games: 64
  max_len: 160
