device: cuda

net:
  num_layers: 8
  dim: 768

train:
  gradient_epochs: 1
  lr: 0.0001
  batch_size: 64
  show_every: 1

self_play:
  num_games: 128
  max_len: 200

pit:
  num_games: 64
  max_len: 160
