class OfflineVisualizer:
    def __init__(self): ...
    def push(self, name, value, epoch): ...
    def html(self, name, value): ...
    def push_range(self, name: str, stats, epoch: int): ...
    def visdom(self, fn, *args, **kwargs): ...


def Visualizer(tag, url, port):
    if url != "offline":
        raise ValueError("remote Visdom support was removed; use Trackio instead")
    return OfflineVisualizer()
