tag: ppo-tdmse
device: cuda
game: connectfour

model: cnn-large

pit:
  every: 20
  max_len: 800
  num_games: 16
  rotate: true
  strategies:
    - policy_sampling,model=this,temperature=0.2
    - random

self_play:
  max_len: 500
  num_games: 96
  rotate: true
  strategies:
    - policy_sampling,model=this,epsilon=0.05
    - policy_sampling,model=this,epsilon=0.05

train:
  optimizer: AdamW
  betas:
    - 0.5
    - 0.999
  batch_size: 256
  print_histories: false
  discount_factor: 1.0
  gradient_epochs: 1
  gae_lambda: 0.98
  reference_model_update: "True"
  losses:
    - policy_gradient_loss,weight=normalized_gae,drift=ppo,imp_ratio_clip=0.2
    - entropy_bonus,strength=0.01
    - adaptive_kl,init_strength=1,target=0.005,deadband=0.001,adaptation_rate=0.1
    - bootstrap_value_mse_loss,strength=1
  lr: 0.0001
  warmup_epochs: 15
  save_every: 50
  show_every: 5
  weight_decay: 0.01
  iterations: 80000
