# Meant to run games without neural network, in order to optimize
# games for speed. I am speed. Gotta go fast.
tag: benchmark
device: cpu
game: tictactoe

model: toy

pit:
  every: 10
  max_len: 220
  num_games: 50
  strategies:
  - random
  - random

self_play:
  max_len: 500
  num_games: 30
  strategies:
  - random
  - random

train:
  optimizer: AdamW
  batch_size: 64
  discount_factor: 1.0
  gradient_epochs: 1
  only_players: []
  losses:
    - policy_gradient_loss,weight=baseline_value,entropy_bonus=0.04,renormalize=False
    - bootstrap_mse_loss,strength=1
  lr: 0.0001
  save_every: 1000
  show_every: 10
