device: cuda
tag: a2c

game: century

model: medium

train:
  optimizer: AdamW
  gradient_epochs: 1
  discount_factor: 0.98
  lr: 0.001
  batch_size: 8
  show_every: 10
  save_every: 10
  #only_players: [0]
  losses:
    - bootstrap_mse_loss,strength=1
    - policy_gradient_loss,entropy_bonus=0.0,weight=advantage,renormalize=True

self_play:
  num_games: 50
  max_len: 200
  batch_size: 50
  strategies:
    - policy_sampling,model=this
    - policy_sampling,model=this

pit:
  num_games: 32
  max_len: 200
  every: 10
  batch_size: 32
  strategies:
    - policy_sampling,model=this,temperature=0.001
    - random_buy
