device: cuda
tag: spo-8sp

game: century

model: cnn

train:
  optimizer: AdamW
  gradient_epochs: 1
  discount_factor: 0.995
  lr: 1e-5
  batch_size: 32
  show_every: 10
  save_every: 10
  gae_lambda: 0.98
  weight_decay: 0.01
  reference_model_update: "True"
  iterations: 8000
  reward_rescale: 0.1
  only_strategies: [0]
  losses:
    - policy_gradient_loss,weight=normalized_gae,drift=spo,imp_ratio_clip=0.2
    - scheduled_perplexity,start=0.3,end=0.1
    - bootstrap_mse_loss,strength=0.1

self_play:
  num_games: 12
  max_len: 200
  batch_size: 50
  strategies:
    - policy_sampling,model=this
    - name: meta_random
      candidates: 
        - weight: 8
          strat: policy_sampling,model=this
        - weight: 2
          strat:
            name: meta_best_opponent
            to: policy_sampling,model=this

pit:
  num_games: 8
  max_len: 200
  every: 10
  batch_size: 32
  rotate: False
  strategies:
    - policy_sampling,model=this
    - random


