device: cuda
tag: reinforce

game: sum

model: medium
train:
  optimizer: AdamW
  gradient_epochs: 1
  discount_factor: 0.8
  lr: 0.0001
  batch_size: 64
  show_every: 10
  save_every: 100
  only_players: [0]
  losses:
    - value_mse_loss,strength=1
    - policy_gradient_loss,weight=baseline_value
    - entropy_bonus,strength=0.05

self_play:
  num_games: 50
  max_len: 500
  strategies:
    - policy_sampling,model=this
    - random

pit:
  num_games: 32
  max_len: 220
  every: 10
  strategies:
    - policy_sampling,model=this
    - random
