device: cpu
tag: dev

net:
  num_layers: 4
  dim: 64
  head_size: 16

train:
  gradient_epochs: 4
  lr: 0.0001
  batch_size: 4
  show_every: 1
  save_every: 10

self_play:
  num_games: 4
  max_len: 200

pit:
  num_games: 8
  max_len: 200
  every: 1
