tag: epita-demo
device: cpu
game: tictactoe

model: tiny

pit:
  every: 25
  max_len: 220
  num_games: 32
  strategies:
  - policy_sampling,model=this
  - random

self_play:
  max_len: 500
  num_games: 32
  strategies:
  - policy_sampling,model=this
  - policy_sampling,model=this

train:
  optimizer: AdamW
  batch_size: 64
  discount_factor: 1.0
  gradient_epochs: 1
  #only_strategies: [1]
  loss:
    policy: policy_gradient_loss,weight=baseline_value,label_smoothing=0.03,renormalize=True
    value: value_mse_loss,strength=1
  lr: 0.00001
  save_every: 1000
  show_every: 10
