tag: epita-demo-recent
device: cpu
game: tictactoe

model: extra-small-deep
train:
  batch_size: 64
  discount_factor: 0.95
  gradient_epochs: 1
  only_players: [0]
  loss:
    policy: policy_gradient_loss,weight=baseline_value,label_smoothing=0.05,renormalize=True
    value: bootstrap_mse_loss,strength=1
  lr: 0.0001
  save_every: 50
  show_every: 10
