tag: a2c
device: cpu
game: guessnumber,num_symbols=2

model: cnn

pit:
  every: 250
  max_len: 220
  num_games: 32
  rotate: false
  strategies:
  - policy_sampling,model=this
  - policy_sampling,model=this

self_play:
  max_len: 500
  num_games: 64
  rotate: true
  strategies:
  - policy_sampling,model=this
  - policy_sampling,model=this

train:
  optimizer: AdamW
  batch_size: 32
  discount_factor: 0.98
  gradient_epochs: 1
  gae_lambda: 0.9
  reference_model_update: "epoch % 1 == 0"
  reward_rescale: 0.1
  losses:
    - policy_gradient_loss,weight=normalized_gae
    - entropy_bonus,strength=0.05
    - bootstrap_mse_loss,strength=0.1
  lr: 0.000001
  save_every: 1000
  show_every: 10
  weight_decay: 0
