device: cuda
tag: century-imitatemc10

net:
  num_layers: 8
  dim: 256
  head_size: 64

train:
  gradient_epochs: 1
  lr: 0.0001
  batch_size: 12
  show_every: 10
  save_every: 10
  loss:
    value: value_mse_loss
    policy: imitation_kl_loss

self_play:
  num_games: 8
  max_len: 500
  strategies:
    - pick_best_mc_value,budget=10
    - pick_best_mc_value,budget=10

pit:
  num_games: 32
  max_len: 220
  every: 4
  strategies:
    - policy_sampling,model=this,temperature=0.001
    - random_buy
