device: cuda
tag: flatbayes-reinforce

game: connectfour

model: medium-deep
train:
  gradient_epochs: 4
  lr: 0.00001
  batch_size: 12
  show_every: 10
  save_every: 10
  discount_factor: 1
  loss:
    value: value_mse_loss,strength=1
    policy: policy_gradient_with_baseline_loss,label_smoothing=0.05

self_play:
  num_games: 4
  max_len: 100
  strategies:
    - minimax_value,budget=5,discount=1
    - minimax_value,budget=5,discount=1

pit:
  num_games: 16
  max_len: 100
  every: 10
  strategies:
    - policy_sampling,model=this
    - random
