device: cuda
tag: lowestcost-supervised

game: thegame,more_than_two_actions=True

model: small
train:
  optimizer: AdamW
  gradient_epochs: 1
  discount_factor: 1.0
  lr: 0.0001
  batch_size: 32
  show_every: 10
  save_every: 100
  losses:
    - value_mse_loss,strength=0.00001
    - ce_loss

self_play:
  num_games: 8
  max_len: 500
  strategies:
    - lowest_cost
    - lowest_cost

pit:
  num_games: 32
  max_len: 220
  every: 100
  strategies:
    - policy_sampling,model=this
    - policy_sampling,model=this
