tag: ppo-temp05
device: cpu
game: thegame

model: cnn

pit:
  every: 99999
  max_len: 80
  num_games: 1
  rotate: false
  strategies:
    - policy_sampling,model=this,temperature=0.5
    - random

self_play:
  max_len: 500
  num_games: 24
  rotate: true
  strategies:
    - policy_sampling,model=this,temperature=0.5
    - policy_sampling,model=this,temperature=0.5

train:
  optimizer: AdamW
  batch_size: 64
  discount_factor: 1.0
  gradient_epochs: 4
  gae_lambda: 0.98
  reference_model_update: "True"
  reward_rescale: 0.1
  losses:
    - policy_gradient_loss,weight=normalized_gae,drift=ppo,imp_ratio_clip=0.2
    - entropy_bonus,strength=0.01
    - kl,strength=0.1
    - bootstrap_mse_loss,strength=0.1
  lr: 0.0005
  save_every: 100
  show_every: 25
  weight_decay: 0
  iterations: 300
