device: cuda
tag: lowestcost-supervised

game: thegame

model: tiny
train:
  optimizer: AdamW
  gradient_epochs: 1
  discount_factor: 0.8
  lr: 0.0001
  batch_size: 32
  show_every: 10
  save_every: 100
  loss:
    value: value_mse_loss,strength=0.1
    policy: ce_loss

self_play:
  num_games: 4
  max_len: 500
  strategies:
    - lowest_cost
    - lowest_cost

pit:
  num_games: 32
  max_len: 220
  every: 100
  strategies:
    - policy_sampling,model=this
    - random
