tag: spo
device: cpu
game: tictactoe

model: cnn

pit:
  every: 10
  max_len: 220
  num_games: 100
  rotate: false
  strategies:
  - policy_sampling,model=this
  - random

self_play:
  max_len: 500
  num_games: 32
  rotate: true
  strategies:
  - policy_sampling,model=this
  - policy_sampling,model=this

train:
  optimizer: AdamW
  batch_size: 64
  discount_factor: 1.0
  gradient_epochs: 1
  reference_model_update: "True"
  #only_strategies: [0]
  losses:
    - policy_gradient_loss,weight=normalized_gae,drift=spo,imp_ratio_clip=0.2
    - scheduled_perplexity,start=0.5,end=0.3
    - bootstrap_mse_loss,strength=0.1
  lr: 5e-5
  save_every: 1000
  show_every: 10
  weight_decay: 0.01
  iterations: 8000
